# Generated by Django 4.1.5 on 2023-01-30 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0034_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
    ]
